version: '3.3'
services:
    l2tp-ipsec-vpn-server:
        container_name: l2tp-ipsec-vpn-server
        environment:
            - ./vpn.env
        ports:
            - '500:500/udp'
            - '4500:4500/udp'
        volumes:
            - '/lib/modules:/lib/modules:ro'
        privileged: true
        image: fcojean/l2tp-ipsec-vpn-server
