version: '3.3'
services:
    vpn-pptp:
        privileged: true
        restart: always
        network_mode: host
        volumes:
            - './chap-secrets:/etc/ppp/chap-secrets'
        image: mobtitude/vpn-pptp
